-- Criação de usuários para cada serviço
CREATE USER sonar WITH PASSWORD 'a12345678';
CREATE USER classes WITH PASSWORD 'a12345678';
CREATE USER courses WITH PASSWORD 'a12345678';
CREATE USER lessons WITH PASSWORD 'a12345678';
CREATE USER professors WITH PASSWORD 'a12345678';
CREATE USER reservations WITH PASSWORD 'a12345678';
CREATE USER resources WITH PASSWORD 'a12345678';
CREATE USER rooms WITH PASSWORD 'a12345678';
CREATE USER students WITH PASSWORD 'a12345678';

-- Criação dos bancos de dados
CREATE DATABASE sonar TEMPLATE template0 ENCODING 'LATIN1' LC_COLLATE 'C' LC_CTYPE 'C' TABLESPACE pg_default CONNECTION LIMIT -1;
CREATE DATABASE classes TEMPLATE template0 ENCODING 'LATIN1' LC_COLLATE 'C' LC_CTYPE 'C' TABLESPACE pg_default CONNECTION LIMIT -1;
CREATE DATABASE courses TEMPLATE template0 ENCODING 'LATIN1' LC_COLLATE 'C' LC_CTYPE 'C' TABLESPACE pg_default CONNECTION LIMIT -1;
CREATE DATABASE lessons TEMPLATE template0 ENCODING 'LATIN1' LC_COLLATE 'C' LC_CTYPE 'C' TABLESPACE pg_default CONNECTION LIMIT -1;
CREATE DATABASE professors TEMPLATE template0 ENCODING 'LATIN1' LC_COLLATE 'C' LC_CTYPE 'C' TABLESPACE pg_default CONNECTION LIMIT -1;
CREATE DATABASE reservations TEMPLATE template0 ENCODING 'LATIN1' LC_COLLATE 'C' LC_CTYPE 'C' TABLESPACE pg_default CONNECTION LIMIT -1;
CREATE DATABASE resources TEMPLATE template0 ENCODING 'LATIN1' LC_COLLATE 'C' LC_CTYPE 'C' TABLESPACE pg_default CONNECTION LIMIT -1;
CREATE DATABASE rooms TEMPLATE template0 ENCODING 'LATIN1' LC_COLLATE 'C' LC_CTYPE 'C' TABLESPACE pg_default CONNECTION LIMIT -1;
CREATE DATABASE students TEMPLATE template0 ENCODING 'LATIN1' LC_COLLATE 'C' LC_CTYPE 'C' TABLESPACE pg_default CONNECTION LIMIT -1;

-- Conceder privilégios aos usuários em seus respectivos bancos
GRANT ALL PRIVILEGES ON DATABASE sonar TO sonar;
GRANT ALL PRIVILEGES ON DATABASE classes TO classes;
GRANT ALL PRIVILEGES ON DATABASE courses TO courses;
GRANT ALL PRIVILEGES ON DATABASE lessons TO lessons;
GRANT ALL PRIVILEGES ON DATABASE professors TO professors;
GRANT ALL PRIVILEGES ON DATABASE reservations TO reservations;
GRANT ALL PRIVILEGES ON DATABASE resources TO resources;
GRANT ALL PRIVILEGES ON DATABASE rooms TO rooms;
GRANT ALL PRIVILEGES ON DATABASE students TO students;

-- Conceder privilégios adicionais necessários
ALTER USER sonar CREATEDB;
ALTER USER classes CREATEDB;
ALTER USER courses CREATEDB;
ALTER USER lessons CREATEDB;
ALTER USER professors CREATEDB;
ALTER USER reservations CREATEDB;
ALTER USER resources CREATEDB;
ALTER USER rooms CREATEDB;
ALTER USER students CREATEDB;
