CREATE DATABASE classes TEMPLATE template0 ENCODING 'LATIN1' LC_COLLATE 'C' LC_CTYPE 'C' TABLESPACE pg_default CONNECTION LIMIT -1;
CREATE DATABASE courses TEMPLATE template0 ENCODING 'LATIN1' LC_COLLATE 'C' LC_CTYPE 'C' TABLESPACE pg_default CONNECTION LIMIT -1;
CREATE DATABASE lessons TEMPLATE template0 ENCODING 'LATIN1' LC_COLLATE 'C' LC_CTYPE 'C' TABLESPACE pg_default CONNECTION LIMIT -1;
CREATE DATABASE professors TEMPLATE template0 ENCODING 'LATIN1' LC_COLLATE 'C' LC_CTYPE 'C' TABLESPACE pg_default CONNECTION LIMIT -1;
CREATE DATABASE reservations TEMPLATE template0 ENCODING 'LATIN1' LC_COLLATE 'C' LC_CTYPE 'C' TABLESPACE pg_default CONNECTION LIMIT -1;
CREATE DATABASE resources TEMPLATE template0 ENCODING 'LATIN1' LC_COLLATE 'C' LC_CTYPE 'C' TABLESPACE pg_default CONNECTION LIMIT -1;
CREATE DATABASE rooms TEMPLATE template0 ENCODING 'LATIN1' LC_COLLATE 'C' LC_CTYPE 'C' TABLESPACE pg_default CONNECTION LIMIT -1;
CREATE DATABASE students TEMPLATE template0 ENCODING 'LATIN1' LC_COLLATE 'C' LC_CTYPE 'C' TABLESPACE pg_default CONNECTION LIMIT -1;
